name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'G'

jobs:
  soft-release:
    name: Soft Release
    runs-on: ubuntu-latest
    steps:
      - name: Staging to Release
        run: |
          sudo apt install wget2
          wget2 https://cdn.waterfox.net/staging/x86_64/Windows_NT/Waterfox\ ${{ github.event.inputs.version }}\ Setup.exe
          wget2 https://cdn.waterfox.net/staging/x86_64/Linux/waterfox-${{ github.event.inputs.version }}.en-US.linux-x86_64.tar.bz2
          wget2 https://cdn.waterfox.net/staging/x86_64/Darwin/Waterfox\ ${{ github.event.inputs.version }}\ Setup.dmg
          wget2 https://cdn.waterfox.net/staging/aarch64/Darwin/Waterfox\ ${{ github.event.inputs.version }}\ ARM\ Setup.dmg 

      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          files: |
            Waterfox\ ${{ github.event.inputs.version }}\ Setup.exe
            waterfox-${{ github.event.inputs.version }}.en-US.linux-x86_64.tar.bz2
            Waterfox\ ${{ github.event.inputs.version }}\ Setup.dmg
            Waterfox\ ${{ github.event.inputs.version }}\ ARM\ Setup.dmg 

      # - name: Rebuild website
      #   run: |
      #     # POST request to Cloudflare endpoint
      #     curl \
      #     -X POST \
      #     -H "content-type": "application/json;charset=UTF-8" \
      #     -H "X-Auth-Email": ${{ secrets.CF_EMAIL }} \
      #     -H "X-Auth-Key": ${{ secrets.CF_API_KEY }} \
      #     https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCT_ID }}/pages/projects/${{ secrets.CF_PROJECT_NAME }}/deployments
          
  hard-release:
    name: Full Release
    needs: [soft-release]
    environment: hard-release
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: fail
      # - name: Copy update.xml
      #   run: |
      #     os=(Windows_NT_x86_64 Linux_x86_64 Darwin_x86_64 Darwin_aarch64)
      #     for i in ${os[@]}
      #     do
      #       update_loc='s3://aus.waterfox.net/update/staging/$i/update.xml'
      #       for j in $(aws s3 ls s3://aus.waterfox.net/update/Waterfox/ | awk '{OFS=" "};{if ($1=="PRE") print $2}')
      #       do
      #         if [[ $j != '/' ]]
      #         then
      #         ver=$(echo $j | sed 's/\///g')
      #         aws s3 cp --content-type="text/xml" --metadata-directive="REPLACE" $update_loc \
      #           s3://aus.waterfox.net/update/Waterfox/$ver/default/$i/update.xml
      #         fi
      #       done
      #       # grab the current version so we can create a new dir with a blank xml
      #       touch blank.xml
      #       echo "<?xml version="1.0"?><updates></updates>" >> blank.xml
      #       aws s3 cp --content-type="text/xml" --metadata-directive="REPLACE" blank.xml \
      #         s3://aus.waterfox.net/update/Waterfox/${{ github.event.inputs.version }}/default/$i/update.xml
      #     done
      - name: Copy installers
        run: |
          rsync -vz --progress kontos@rsync.keycdn.com:waterfox/staging/x86_64/Windows_NT/Waterfox\ ${{ github.event.inputs.version }}\ Setup.exe kontos@rsync.keycdn.com:waterfox/releases/win64/installer/
          rsync -vz --progress kontos@rsync.keycdn.com:waterfox/staging/x86_64/Linux/waterfox-${{ github.event.inputs.version }}.en-US.linux-x86_64.tar.bz2 kontos@rsync.keycdn.com:waterfox/releases/linux64/installer/
          rsync -vz --progress kontos@rsync.keycdn.com:waterfox/staging/x86_64/Darwin/Waterfox\ ${{ github.event.inputs.version }}\ Setup.dmg kontos@rsync.keycdn.com:waterfox/releases/osx64/installer/
          rsync -vz --progress kontos@rsync.keycdn.com:waterfox/staging/aarch64/Darwin/Waterfox\ ${{ github.event.inputs.version }}\ ARM\ Setup.dmg kontos@rsync.keycdn.com:waterfox/releases/osx64/installer/

